name: Promotion Issue Form Opened

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  get_issue_info:
    runs-on: ubuntu-latest
    outputs:
      organisation: ${{ steps.extract_issue_title.outputs.organisation }}
      repository: ${{ steps.extract_issue_body.outputs.repository }}
    steps:
      - id: extract_issue_title
        env:
          ORG: ${{ github.event.issue.title }}
        run: echo "::set-output name=organisation::$ORG"
      - id: extract_issue_body
        env:
          REPO: ${{ github.event.issue.body }}
        run: echo "::set-output name=repository::$REPO"

  update_repo_visibility:
    name: Update Repo Visibility
    environment: Production
    runs-on: ubuntu-20.04
    needs: get_issue_info
    
    steps:
      - name: Get Shortlived Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ env.organisation }}
        env:
          organisation: ${{ needs.get_issue_info.outputs.organisation }}
      
      - uses: octokit/request-action@v2.x
        id: update_repository_visibility
        with:
          route: PATCH /repos/{owner}/{repo}
          owner: ${{ env.organisation }}
          repo: ${{ env.repository }}
          visibility: "internal"
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          organisation: ${{ needs.get_issue_info.outputs.organisation }}
          repository: ${{ needs.get_issue_info.outputs.repository }}
